---
- hosts: all
  tasks:
    - name: Create data directories
      become: yes
      file:
        path: "{{ item.path }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "0770"
        state: directory
      with_items:
        - path: "/data/recentglobe"
          owner: "{{ username }}"
          group: recentglobe
        - path: "/app/recentglobe"
          owner: "{{ username }}"
          group: recentglobe
