---
- hosts: all
  become: true
  vars_files:
    - group_vars/all/main.yml
  pre_tasks:
    - name: Update package cache and install admin tools
      apt:
        name:
          - htop
          - dstat
          - ncdu
        update_cache: true
  roles:
    - geerlingguy.docker
    - common
    - zsh
    - geerlingguy.firewall
    - geerlingguy.security
    - geerlingguy.pip
    - weareinteractive.apt
